language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt 
# command to run tests
env:
  - DJANGO_VERSION=1.5
before_script:
  - ./start_local_candideitorg.bash
script:
  - python manage.py test candideitorg
